version: "3.0"
services:
    frontend:
      image: ${FRONTEND_REGISTRY}:${FRONTEND_TAG}
      ports:
        - "80:80"
      volumes:
        - ./backend.conf:/etc/nginx/proxy.d/backend.conf
      depends_on:
        - "molgenis"
    molgenis:
      image: ${BACKEND_REGISTRY}:${BACKEND_TAG}
      user: 0:0
      environment:
        - environment=development
        - molgenis.home=/home/molgenis
        - opencpu.uri.host=opencpu
        - elasticsearch.transport.addresses=elasticsearch:9300
        - db_uri=jdbc:postgresql://postgres/molgenis
        - db_user=molgenis
        - db_password=molgenis
        - admin.password=admin
        - MINIO_BUCKET_NAME=molgenis
        - MINIO_ENDPOINT=http://minio:9000
        - MINIO_ACCESS_KEY=molgenis
        - MINIO_SECRET_KEY=molgenis
        - MOLGENIS_MAX_FILE_MB=150
        - "CATALINA_OPTS=-Xmx1g -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
        - audit.log.path=/home/molgenis/audit/audit.log
      expose:
        - "8080"
      volumes:
        - app-data:/home/molgenis
        - audit-log:/home/molgenis/audit
      depends_on:
        - postgres
    postgres:
      image: postgres:11-alpine
      environment:
        - POSTGRES_USER=molgenis
        - POSTGRES_PASSWORD=molgenis
        - POSTGRES_DB=molgenis
      expose:
        - "5432"
      volumes:
        - db-data:/var/lib/postgresql/data
      command: -c 'shared_buffers=256MB' -c 'max_locks_per_transaction=1024' 
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
        environment:
          - cluster.name=molgenis
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          - xpack.security.enabled=false
          - discovery.type=single-node
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
          - es-data:/usr/share/elasticsearch/data
        ports:
          - 9200:9200
          - 9300:9300
    kibana:
      image: docker.elastic.co/kibana/kibana:5.5.3
      profiles:
        - audit
      ports:
        - 5601:5601
    kibana-dashboard:
      user: 0:0
      image: docker.elastic.co/kibana/kibana:5.5.3
      profiles:
        - audit
      command:
        - "/bin/sh"
        - "-c"
        - "/root/dashboard/import.sh"
      environment:
        DASHBOARD_FILE: https://raw.githubusercontent.com/molgenis/molgenis/master/.kibana/dashboard.json
      volumes:
        - ./dashboard:/root/dashboard:ro
    filebeat:
      image: docker.elastic.co/beats/filebeat-oss:7.9.3
      profiles:
        - audit
      environment:
        ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      volumes:
        - audit-log:/usr/share/filebeat/input/
        - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      depends_on:
        - elasticsearch
    opencpu:
        image: molgenis/opencpu:opencpu-release-2019-03-20_12-07-11
        profiles:
          - opencpu
        ports:
          - 8004:8004
    minio:
      image: minio/minio:RELEASE.2019-03-20T22-38-47Z
      volumes:
        - minio-data:/data
      ports:
        - 9000:9000
      environment:
        MINIO_ACCESS_KEY: molgenis
        MINIO_SECRET_KEY: molgenis
      command: server /data
volumes:
    audit-log:
    db-data:
    app-data:
    es-data:
    minio-data:
        driver: local